import { randomUUID } from "node:crypto";
import type { DatabaseSync } from "node:sqlite";
import { transaction } from "./database.js";
import { event } from "./events.js";
import { AppError } from "./errors.js";

/**
 * Machine-local career facts, bullets and base-resume templates, stored as immutable
 * revisions. Nothing here is generated by a model; it is the operator's own material,
 * imported from selected files or edited directly. A render references exact revisions.
 */
export type Fact = { key: string; value: string; source?: string | null; verified: boolean };
export type ProfileData = {
  contact: { name: string; email?: string | null; phone?: string | null; location?: string | null; links?: string[] | null };
  summary?: string | null;
  /** Operator-confirmed facts. `suggestions` are explicitly unverified. */
  facts: Fact[];
  suggestions: Fact[];
};
export type BulletInput = {
  bulletId: string; prose: string; tags: string[];
  /** Structured, non-prose context (employer, role, dates) used for ordering/evidence. */
  filters?: Record<string, unknown> | null; evidence?: unknown;
};
export type TemplateSection =
  | { id: string; title: string; type: "facts"; factKeys: string[]; optional?: boolean }
  | { id: string; title: string; type: "tags" }
  | { id: string; title: string; type: "bullets"; limit: number; order?: "most-relevant" | "as-listed" };
export type TemplateData = { name: string; sections: TemplateSection[] };

export type ProfileRevision = { id: string; profileId: string; revision: number; data: ProfileData; evidence: unknown; createdAt: string };
export type BulletRevision = { id: string; bulletId: string; revision: number; profileRevisionId: string; prose: string; tags: string[]; filters: Record<string, unknown>; evidence: unknown; createdAt: string };
export type TemplateRevision = { id: string; templateId: string; revision: number; data: TemplateData; createdAt: string };

const asRecord = (value: unknown): Record<string, unknown> => (value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : {});
const clean = (value: unknown, max: number): string | null => (typeof value === "string" && value.trim() ? value.trim().slice(0, max) : null);

/** Validation happens before anything is stored; the renderer only ever sees validated data. */
export function validateProfileData(input: unknown): ProfileData {
  const value = asRecord(input);
  const contact = asRecord(value["contact"]);
  const name = clean(contact["name"], 200);
  if (!name) throw new AppError("invalid_profile", "Profile contact.name is required");
  const links = Array.isArray(contact["links"]) ? contact["links"].map(link => clean(link, 500)).filter((link): link is string => Boolean(link)) : [];
  const facts = (array: unknown, label: string, verified: boolean): Fact[] => {
    if (array === undefined) return [];
    if (!Array.isArray(array)) throw new AppError("invalid_profile", `${label} must be an array`);
    return array.map((entry, index) => {
      const fact = asRecord(entry);
      const key = clean(fact["key"], 100);
      const valueText = clean(fact["value"], 4000);
      if (!key || !valueText) throw new AppError("invalid_profile", `${label}[${index}] needs key and value`);
      return { key, value: valueText, source: clean(fact["source"], 500), verified: verified && fact["verified"] !== false };
    });
  };
  return {
    contact: { name, email: clean(contact["email"], 320), phone: clean(contact["phone"], 64), location: clean(contact["location"], 200), links },
    summary: clean(value["summary"], 4000),
    facts: facts(value["facts"], "facts", true),
    suggestions: facts(value["suggestions"], "suggestions", false),
  };
}

export function validateTemplateData(input: unknown): TemplateData {
  const value = asRecord(input);
  const name = clean(value["name"], 200);
  const sections = value["sections"];
  if (!name) throw new AppError("invalid_template", "Template name is required");
  if (!Array.isArray(sections) || sections.length === 0) throw new AppError("invalid_template", "Template needs at least one section");
  const seen = new Set<string>();
  const validated: TemplateSection[] = sections.map((entry, index): TemplateSection => {
    const section = asRecord(entry);
    const id = clean(section["id"], 100), title = clean(section["title"], 200), type = section["type"];
    if (!id || !title) throw new AppError("invalid_template", `sections[${index}] needs id and title`);
    if (seen.has(id)) throw new AppError("invalid_template", `Duplicate section id ${id}`);
    seen.add(id);
    if (type === "facts") {
      const factKeys = Array.isArray(section["factKeys"]) ? section["factKeys"].map(key => clean(key, 100)).filter((key): key is string => Boolean(key)) : [];
      if (!factKeys.length) throw new AppError("invalid_template", `sections[${index}] needs factKeys`);
      return { id, title, type: "facts", factKeys, optional: section["optional"] === true };
    }
    if (type === "tags") return { id, title, type: "tags" };
    if (type === "bullets") {
      const limit = Number(section["limit"] ?? 0);
      if (!Number.isSafeInteger(limit) || limit < 1 || limit > 50) throw new AppError("invalid_template", `sections[${index}].limit must be 1–50`);
      return { id, title, type: "bullets", limit, order: section["order"] === "as-listed" ? "as-listed" : "most-relevant" };
    }
    throw new AppError("invalid_template", `sections[${index}].type must be facts, tags or bullets`);
  });
  return { name, sections: validated };
}

export function validateBullets(input: unknown): BulletInput[] {
  if (!Array.isArray(input) || input.length === 0) throw new AppError("invalid_bullets", "At least one bullet is required");
  const seen = new Set<string>();
  return input.map((entry, index) => {
    const bullet = asRecord(entry);
    const bulletId = clean(bullet["bulletId"], 100), prose = clean(bullet["prose"], 4000);
    if (!bulletId || !prose) throw new AppError("invalid_bullets", `bullets[${index}] needs bulletId and prose`);
    if (seen.has(bulletId)) throw new AppError("invalid_bullets", `Duplicate bulletId ${bulletId}`);
    seen.add(bulletId);
    const tags = Array.isArray(bullet["tags"]) ? bullet["tags"].map(tag => clean(tag, 60)).filter((tag): tag is string => Boolean(tag)) : [];
    return { bulletId, prose, tags, filters: bullet["filters"] === undefined ? null : asRecord(bullet["filters"]), evidence: bullet["evidence"] ?? null };
  });
}

const mapProfile = (row: Record<string, unknown>): ProfileRevision => ({
  id: String(row["id"]), profileId: String(row["profile_id"]), revision: Number(row["revision"]),
  data: JSON.parse(String(row["data_json"])) as ProfileData, evidence: JSON.parse(String(row["evidence_json"])),
  createdAt: String(row["created_at"]),
});
const mapBullet = (row: Record<string, unknown>): BulletRevision => ({
  id: String(row["id"]), bulletId: String(row["bullet_id"]), revision: Number(row["revision"]),
  profileRevisionId: String(row["profile_revision_id"]), prose: String(row["prose"]),
  tags: JSON.parse(String(row["tags_json"])) as string[], filters: JSON.parse(String(row["filters_json"])) as Record<string, unknown>,
  evidence: JSON.parse(String(row["evidence_json"])), createdAt: String(row["created_at"]),
});
const mapTemplate = (row: Record<string, unknown>): TemplateRevision => ({
  id: String(row["id"]), templateId: String(row["template_id"]), revision: Number(row["revision"]),
  data: JSON.parse(String(row["data_json"])) as TemplateData, createdAt: String(row["created_at"]),
});

export class Library {
  constructor(readonly db: DatabaseSync, readonly now: () => number = Date.now) {}
  profiles(): ProfileRevision[] {
    return (this.db.prepare(`SELECT p.* FROM profile_revisions p JOIN (SELECT profile_id,max(revision) AS revision FROM profile_revisions GROUP BY profile_id) m
      ON m.profile_id=p.profile_id AND m.revision=p.revision ORDER BY p.profile_id`).all() as Record<string, unknown>[]).map(mapProfile);
  }
  profile(id: string): ProfileRevision | null {
    const row = this.db.prepare("SELECT * FROM profile_revisions WHERE id=?").get(id) as Record<string, unknown> | undefined;
    return row ? mapProfile(row) : null;
  }
  latestProfile(profileId?: string): ProfileRevision | null {
    const row = profileId
      ? this.db.prepare("SELECT * FROM profile_revisions WHERE profile_id=? ORDER BY revision DESC LIMIT 1").get(profileId)
      : this.db.prepare("SELECT * FROM profile_revisions ORDER BY created_at DESC, rowid DESC LIMIT 1").get();
    return row ? mapProfile(row as Record<string, unknown>) : null;
  }
  templates(): TemplateRevision[] {
    return (this.db.prepare(`SELECT t.* FROM template_revisions t JOIN (SELECT template_id,max(revision) AS revision FROM template_revisions GROUP BY template_id) m
      ON m.template_id=t.template_id AND m.revision=t.revision ORDER BY t.template_id`).all() as Record<string, unknown>[]).map(mapTemplate);
  }
  template(id: string): TemplateRevision | null {
    const row = this.db.prepare("SELECT * FROM template_revisions WHERE id=?").get(id) as Record<string, unknown> | undefined;
    return row ? mapTemplate(row) : null;
  }
  /** Latest revision of each bullet within one profile revision. */
  bullets(profileRevisionId: string): BulletRevision[] {
    return (this.db.prepare(`SELECT b.* FROM bullet_revisions b JOIN (SELECT bullet_id,max(revision) AS revision FROM bullet_revisions
      WHERE profile_revision_id=? GROUP BY bullet_id) m ON m.bullet_id=b.bullet_id AND m.revision=b.revision
      WHERE b.profile_revision_id=? ORDER BY b.bullet_id`).all(profileRevisionId, profileRevisionId) as Record<string, unknown>[]).map(mapBullet);
  }

  /**
   * Each profile revision owns its bullet set. By default a new revision carries the previous
   * revision's current bullets forward (as new, identical bullet revisions), so correcting a
   * contact detail never empties the library; `carryBullets: false` starts an empty set, which
   * is how bullets are retired.
   */
  addProfile(input: { profileId: string; data: unknown; evidence?: unknown; carryBullets?: boolean }): ProfileRevision {
    const profileId = clean(input.profileId, 100);
    if (!profileId) throw new AppError("invalid_profile", "profileId is required");
    const data = validateProfileData(input.data);
    return transaction(this.db, () => {
      const previous = this.latestProfile(profileId);
      const next = (previous?.revision ?? 0) + 1;
      const id = randomUUID();
      this.db.prepare("INSERT INTO profile_revisions(id,profile_id,revision,data_json,evidence_json,created_at) VALUES(?,?,?,?,?,?)")
        .run(id, profileId, next, JSON.stringify(data), JSON.stringify(input.evidence ?? { source: "operator" }), new Date(this.now()).toISOString());
      const carried = previous && input.carryBullets !== false
        ? this.#insertBullets(id, this.bullets(previous.id).map(bullet => ({ bulletId: bullet.bulletId, prose: bullet.prose, tags: bullet.tags,
          filters: bullet.filters, evidence: { carriedFrom: bullet.id } }))).length
        : 0;
      event(this.db, "library.profile", "profile", profileId, { revision: next, id, carriedBullets: carried }, this.now());
      return this.profile(id)!;
    });
  }
  addBullets(input: { profileRevisionId: string; bullets: unknown }): BulletRevision[] {
    const profile = this.profile(input.profileRevisionId);
    if (!profile) throw new AppError("profile_missing", "Profile revision not found", 404);
    const bullets = validateBullets(input.bullets);
    return transaction(this.db, () => {
      const created = this.#insertBullets(input.profileRevisionId, bullets);
      event(this.db, "library.bullets", "profile", profile.profileId, { count: created.length, revision: profile.revision }, this.now());
      return created.map(id => this.bullet(id)!);
    });
  }
  /** Appends bullet revisions; the caller owns the transaction. */
  #insertBullets(profileRevisionId: string, bullets: BulletInput[]): string[] {
    const created: string[] = [];
    for (const bullet of bullets) {
      const next = Number((this.db.prepare("SELECT max(revision) AS revision FROM bullet_revisions WHERE bullet_id=?").get(bullet.bulletId) as Record<string, unknown>)["revision"] ?? 0) + 1;
      const id = randomUUID();
      this.db.prepare(`INSERT INTO bullet_revisions(id,bullet_id,revision,profile_revision_id,prose,tags_json,filters_json,evidence_json,created_at)
        VALUES(?,?,?,?,?,?,?,?,?)`).run(id, bullet.bulletId, next, profileRevisionId, bullet.prose,
        JSON.stringify(bullet.tags), JSON.stringify(bullet.filters ?? {}), JSON.stringify(bullet.evidence ?? {}), new Date(this.now()).toISOString());
      created.push(id);
    }
    return created;
  }
  bullet(id: string): BulletRevision | null {
    const row = this.db.prepare("SELECT * FROM bullet_revisions WHERE id=?").get(id) as Record<string, unknown> | undefined;
    return row ? mapBullet(row) : null;
  }
  addTemplate(input: { templateId: string; data: unknown }): TemplateRevision {
    const templateId = clean(input.templateId, 100);
    if (!templateId) throw new AppError("invalid_template", "templateId is required");
    const data = validateTemplateData(input.data);
    return transaction(this.db, () => {
      const next = Number((this.db.prepare("SELECT max(revision) AS revision FROM template_revisions WHERE template_id=?").get(templateId) as Record<string, unknown>)["revision"] ?? 0) + 1;
      const id = randomUUID();
      this.db.prepare("INSERT INTO template_revisions(id,template_id,revision,data_json,created_at) VALUES(?,?,?,?,?)")
        .run(id, templateId, next, JSON.stringify(data), new Date(this.now()).toISOString());
      event(this.db, "library.template", "template", templateId, { revision: next, id }, this.now());
      return this.template(id)!;
    });
  }

  /** The current library: latest profiles and templates, and each exported profile's current bullets. */
  exportAll(): { schemaVersion: 1; profiles: ProfileRevision[]; bullets: BulletRevision[]; templates: TemplateRevision[] } {
    const profiles = this.profiles();
    return { schemaVersion: 1, profiles, templates: this.templates(), bullets: profiles.flatMap(profile => this.bullets(profile.id)) };
  }
  /** Importing creates new revisions; existing history is never rewritten. */
  importAll(payload: unknown): { profiles: number; bullets: number; templates: number } {
    const value = asRecord(payload);
    if (value["schemaVersion"] !== 1) throw new AppError("invalid_import", "Unsupported library export version");
    let profiles = 0, bulletCount = 0, templates = 0;
    const profileMapping = new Map<string, string>();
    for (const entry of (Array.isArray(value["profiles"]) ? value["profiles"] : [])) {
      const item = asRecord(entry);
      // The import states the bullet set explicitly, so nothing is carried from a local revision.
      const added = this.addProfile({ profileId: String(item["profileId"] ?? ""), data: item["data"], evidence: item["evidence"], carryBullets: false });
      profileMapping.set(String(item["id"] ?? ""), added.id); profiles++;
    }
    for (const entry of (Array.isArray(value["templates"]) ? value["templates"] : [])) {
      this.addTemplate({ templateId: String(asRecord(entry)["templateId"] ?? ""), data: asRecord(entry)["data"] }); templates++;
    }
    const grouped = new Map<string, Map<string, { revision: number; bullet: BulletInput }>>();
    for (const entry of (Array.isArray(value["bullets"]) ? value["bullets"] : [])) {
      const item = asRecord(entry);
      const target = profileMapping.get(String(item["profileRevisionId"] ?? ""));
      if (!target) continue;
      // Older exports listed every revision; keep only the highest revision of each bullet.
      const list = grouped.get(target) ?? new Map<string, { revision: number; bullet: BulletInput }>();
      const bulletId = String(item["bulletId"] ?? ""), revision = Number(item["revision"] ?? 0);
      if ((list.get(bulletId)?.revision ?? -Infinity) <= revision)
        list.set(bulletId, { revision, bullet: { bulletId, prose: String(item["prose"] ?? ""), tags: Array.isArray(item["tags"]) ? item["tags"] as string[] : [], filters: asRecord(item["filters"]), evidence: item["evidence"] } });
      grouped.set(target, list);
    }
    for (const [profileRevisionId, list] of grouped) { this.addBullets({ profileRevisionId, bullets: [...list.values()].map(entry => entry.bullet) }); bulletCount += list.size; }
    return { profiles, bullets: bulletCount, templates };
  }
}
